# Exploratory Data Analysis on Laptop Price Dataset

## Description
This project analyzes laptop prices based on features like RAM, processor, and storage.

## Status
Project initialized.

## Data Loading and Initial Inspection

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("../data/laptop_price.csv", encoding='latin-1')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [3]:
print("Shape of the dataset:",df.shape)
df.info()
df.describe()

Shape of the dataset: (1303, 13)
<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Memory            1303 non-null   str
 9   Gpu               1303 non-null   str
 10  OpSys             1303 non-null   str
 11  Weight            1303 non-null   str
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(10)
memory usage: 132.5 KB

         laptop_ID       Inches  Price_euros
count  1303.000000  1303.000000  1303.000000
mean    660.155794    15.017191  1123.686992
std     381.172104     1.426304   699.009043
min       1.000000    10.100000   174.000000
25%     331.500000    14.000000   599.000000
50%     659.000000    15.600000   977.000000
75%     990.500000    15.600000  1487.880000
max    1320.000000    18.400000  6099.000000

In [4]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

## Initial Observations

- Dataset loaded successfully
- Contains multiple features related to laptop specifications
- No columns contains missing values
- Further cleaning and analysis required

## Data Cleaning

In [8]:
df = df.ffill()
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

Since 0 duplicate value is there, therefore no need to remove the duplicates.
otherwise we would use 
    df = df.drop_duplicates()

In [10]:
df.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='str')

In [11]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_id         1303 non-null   int64
 1   company           1303 non-null   str
 2   product           1303 non-null   str
 3   typename          1303 non-null   str
 4   inches            1303 non-null   float64
 5   screenresolution  1303 non-null   str
 6   cpu               1303 non-null   str
 7   ram               1303 non-null   str
 8   memory            1303 non-null   str
 9   gpu               1303 non-null   str
 10  opsys             1303 non-null   str
 11  weight            1303 non-null   str
 12  price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(10)
memory usage: 132.5 KB



### ✅ Correct Data Types

* `price_euros` → **float**
* `inches` → **float**
* `laptop_id` → **int**

---

### ⚠️ Should NOT Be Strings

* `ram` → values like `"8GB"`
* `weight` → values like `"2.3kg"`

👉 These should be **converted to numeric types** (e.g., `8`, `2.3`) for proper analysis and processing.

### Fix RAM column

In [13]:
df['ram'] = df['ram'].str.replace('GB', '')
df['ram'] = df['ram'].astype(int)

### Fix Weight column

In [14]:
df['weight'] = df['weight'].str.replace('kg', '')
df['weight'] = df['weight'].astype(float)

In [15]:
df.to_csv("../data/cleaned_laptop_price.csv", index=False)